#!/usr/bin/env bash
# this script uses while loop to display "Best School" 8 times
# hi on 9th time and back on 10th time

cnt=0

while [ $cnt -lt 10 ]
do
if [ $cnt -eq 3 ]
then
echo "bad luck"
elif [ $cnt -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((cnt++))
done
